### ISSUE TITLE
Release spring-build-conventions 0.0.18

### ISSUE THREAD

**Issue by rwinch** [spring-gradle-plugins/spring-build-conventions#36]

**Comment by vpavic** [comment]
Note that with this release, consuming projects that use Checkstyle need to update references to configuration directory from `configDir` to [more standard `config_loc`](https://docs.gradle.org/current/userguide/checkstyle_plugin.html#sec:checkstyle_built_in_variables).

For example, see Spring Session's [`checkstyle.xml`](https://github.com/spring-projects/spring-session/blob/master/etc/checkstyle/checkstyle.xml#L7).
