### ISSUE TITLE
spring security oauth2 to support http schema to refer local xsd to support backward compatible  

### ISSUE THREAD

**Issue by prabhu-radhakrishna** [spring-gradle-plugins/spring-build-conventions#92]
we need to support both http&https in https://github.com/spring-projects/spring-security-oauth/commits/master/spring-security-oauth2/src/main/resources/META-INF/spring.schemas  
 like any other spring schemas  https://github.com/spring-projects/spring-security/blob/master/config/src/main/resources/META-INF/spring.schemas

even https://github.com/spring-io/nohttp/tree/master/nohttp  supports using http for namespace

**Comment by rwinch** [comment]
Thanks for the report. I think you have created this issue in the wrong repository by mistake. Is there a reason you created the issue here vs in the repository that you are linking to (spring-projects/spring-security-oauth)?

**Comment by jgrandja** [comment]
Closing as duplicate [spring-security-oauth#1917](https://github.com/spring-projects/spring-security-oauth/issues/1917)
